name: Node.js CI/CD with NPM
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can adjust the version as needed
 
    - name: Install dependencies
      run: npm install
      
    - name: unit test
      run: npm run test:unit
      continue-on-error: true
 
    - name: bdd test
      run: npm run test:bdd
      continue-on-error: true
      
    - name: atdd test
      run: npm run test:atdd
      continue-on-error: true
